version: '3.9'

volumes:
  omd-sites:
  cmk-backup:

services:
  check_mk:
    build:
      dockerfile: Dockerfile
      context: .
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    ulimits:
      nofile:
        soft: 1024
        hard: 1024
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - cmk-backup:/mnt/backup
      - omd-sites:/omd/sites
    ports:
      - 8080:5000
      - 6557:6557
    environment:
      - CMK_SITE_ID=${CMK_SITE_ID}
      - CMK_PASSWORD=${CMK_PASSWORD}
